# Generated by Django 4.1.2 on 2022-10-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0003_employee_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('worker', models.ManyToManyField(related_name='orders', to='employees.employee')),
            ],
        ),
    ]
