# Generated by Django 4.1.2 on 2022-10-22 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='job',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='employee', to='employees.jobtitles'),
            preserve_default=False,
        ),
    ]
